<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="ValidaTarjetaCreditoServicio"
     targetNamespace="http://oracle.com/sca/soapservice/TarjetaCreditoValidacion/tarjetaCreditoValidacion/ValidaTarjetaCreditoServicio"
     xmlns:tns="http://oracle.com/sca/soapservice/TarjetaCreditoValidacion/tarjetaCreditoValidacion/ValidaTarjetaCreditoServicio"
     xmlns:inp1="http://www.example.org"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.example.org" schemaLocation="../Schemas/TarjetaCreditoValidacion.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="ValidaTarjetaCreditoPeticion" element="inp1:Peticion"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="ValidaTarjetaCreditoRespuesta" element="inp1:Respuesta"/>
    </wsdl:message>
    <wsdl:message name="faultMessage">
        <wsdl:part name="Fallo" element="inp1:Fallo"/>
    </wsdl:message>
    <wsdl:portType name="execute_ptt">
        <wsdl:operation name="validaTarjetaCredito">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
            <wsdl:fault name="validaTarjetaCreditofault" message="tns:faultMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
