---------------------------------------------
-- TARJETAS DE CREDITO PARA EL DEMO DE SOA --
---------------------------------------------


INSERT INTO "SOADEMO"."TARJETACREDITOINFO" (TITULARNOMBRE, TITULARAPELLIDO, NUMERO, ESTATUS)
VALUES ('CARLOS', 'MARQUEZ', '5678-5678-5678-5678', 'INVALIDA');
INSERT INTO "SOADEMO"."TARJETACREDITOINFO" (TITULARNOMBRE, TITULARAPELLIDO, NUMERO, ESTATUS)
VALUES ('JUAN', 'LOPEZ', '1234-1234-1234-1234', 'VALIDA');
INSERT INTO "SOADEMO"."TARJETACREDITOINFO" (TITULARNOMBRE, TITULARAPELLIDO, NUMERO, ESTATUS)
VALUES ('JORGE', 'SANTOS', '9876-9876-9876-9876', 'VALIDA');
INSERT INTO "SOADEMO"."TARJETACREDITOINFO" (TITULARNOMBRE, TITULARAPELLIDO, NUMERO, ESTATUS)
VALUES ('LUIS', 'GODINEZ', '6542-6542-6542-6542', 'INVALIDA');
INSERT INTO "SOADEMO"."TARJETACREDITOINFO" (TITULARNOMBRE, TITULARAPELLIDO, NUMERO, ESTATUS)
VALUES ('DANIEL', 'GUTIERREZ', '9425-9425-9425-9425', 'VALIDA');
INSERT INTO "SOADEMO"."TARJETACREDITOINFO" (TITULARNOMBRE, TITULARAPELLIDO, NUMERO, ESTATUS)
VALUES ('SOFIA', 'GARCIA', '9513-9513-9513-9513', 'INVALIDA');
